name: Feature Request
description: Aggiungi una nuova funzione
title: 'feat: [descrizione breve]'
labels: ['feature', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Descrivi la feature che vorresti aggiungere in modo chiaro e dettagliato.

  - type: textarea
    id: description
    attributes:
      label: Descrizione
      description: "Spiega cosa vorresti aggiungere e perche'."
      placeholder: "Aggiungere la funzione di login e' necessaria per permettere agli utenti di accedere alle aree riservate"
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Criteri di Accettazione
      description: "Elenca i criteri per considerare completa la issue (Il Cosa)."
      placeholder: |
        - Presenza del form di login
        - Validazione lato client funzionante
        - Reindirizzamento corretto dopo l'accesso
    validations:
      required: true

  - type: textarea
    id: task
    attributes:
      label: Task
      description: 'Elenca i passaggi tecnici necessari per completare la feature (Il Come).'
      placeholder: |
        - [ ] Creare componente UI del bottone
        - [ ] Implementare logica di autenticazione
        - [ ] Aggiornare i test

  - type: textarea
    id: notes
    attributes:
      label: Note aggiuntive (opzionale)
      placeholder: 'Qualsiasi altra info utile (es. link alla documentazione, dipendenze da installare, screenshots, esempi)'